#! /bin/bash

brew install qmk/qmk/qmk
mkdir -p ~/projects/keyboards
qmk setup -y --home ~/projects/keyboards/qmk_firmware
qmk config user.keyboard=crkbd/r2g
qmk compile -kb crkbd/r2g -km default
echo "QMK Ready to build"

echo "Setting up personal keymaps"
ln -sf ../../../../crkbd/Ad01 qmk_firmware/keyboards/crkbd/keymaps/Ad01

echo "Ready- Let's break some keyboards!"
