LTO_ENABLE        = yes
OLED_ENABLE       = yes
OLED_DRIVER       = SSD1306
RGBLIGHT_ENABLE   = yes
RGBLIGHT_SLEEP    = yes
AUTO_SHIFT_ENABLE = yes
COMBO_ENABLE 			= yes
POINTING_DEVICE_ENABLE = yes

# Space saving
AUDIO_ENABLE      = no
CONSOLE_ENABLE    = no
COMMAND_ENABLE    = no
MOUSEKEY_ENABLE   = no
VIA_ENABLE        = no
WPM_ENABLE        = no
